# Welcome to Cusing Memorial Park!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Piping Queen Apiary
email: kkrausesc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Cushiing Memorial Park
baseurl: "" # the subpath of your site, e.g. /blog
url: "WWW.PIPINGQUEEN.NET" # the base hostname & protocol for your site
twitter_username: 
github_username:  kdcain27

# Build settings
markdown: kramdown
